shiny:
  proxy:
    heartbeat-rate: 10000
    heartbeat-timeout: 60000
    port: 8080
    authentication: ldap
    admin-groups: simple
    # Example: 'simple' authentication configuration
    users:
    - name: jack
      password: password
      groups: scientists
    - name: jeff
      password: password
      groups: mathematicians
    # Docker configurati

logging:
  file: shinyproxy.log
